### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by mpalladi** [PTCInc/twx-solution-framework#1]
I have followed the installation instructions, and the Initialize Service returns a good result, but the PTC.SolutionFramework.Main_MU mashup fails to load.

<img width="1583" alt="Screen Shot 2022-03-01 at 5 11 02 pm" src="https://user-images.githubusercontent.com/23260676/156144057-fb23f9a6-af72-46b2-81b1-1c4160e66203.png">
<img width="1583" alt="Screen Shot 2022-03-01 at 5 40 25 pm" src="https://user-images.githubusercontent.com/23260676/156144371-965da9f8-5bd2-4a53-ad3a-758baeea2d40.png">

**Comment by mvulcano-ptc** [comment]
Hello,

Can you find the PTC.DBConnection.Manager Thing in Composer, and tell me what 'defaultDatabaseConnection' is configured on its configuration page? 

It looks like you just have the MFG Common Building Blocks installed, and not DPM. This is not an issue. However, even though DPM is not installed, in its current state the DBConnection Database Connection either needs to be null, or valid. 

Once you verify what Database Connection is configured on the DBConnection Manager, please click through to open that thing (either PTC.DBConnection.MSSQLDatabase or PTC.DBConnection.PostgresDatabase) and verify that the database connection is successfully configured:

- Navigate to the Database Connection Thing
- Click on Properties
- Verify that 'isConnected' is true

If the connection is not true, adjust the JDBC configurations on the thing so that it can make a valid connection. If the wrong database connection thing is configured on PTC.DBConnection.Manager, simply change that configuration so that the correct one is configured. Lastly, if you do not have a database for it to connect to, remove the configured database connection config and leave it null.

Any one of the above actions should resolve the issue you are seeing above.

Please let me know if this helps, and if you are still experiencing issues after the above steps, if you could attach the error from the Script log that would be helpful.

Matt.

**Comment by mpalladi** [comment]
Hi Matt

Thanks for taking the time to respond.. so quickly

The MS SQL Database is connected, the connection is the database that was initialised when I after following the steps installing building blocks here
https://support.ptc.com/help/building_blocks/r1.0/en/#page/bb%2Fbuilding_blocks%2Fgetting_started_with_building_blocks%2Fdeploying_building_blocks.html%23

[ScriptErrorLog.log](https://github.com/PTCInc/twx-solution-framework/files/8162069/ScriptErrorLog.log)
<img width="1036" alt="Screen Shot 2022-03-01 at 9 50 42 pm" src="https://user-images.githubusercontent.com/23260676/156182756-d2d81cc0-6c7e-4c63-96a1-6b31eab10f7c.png">
<img width="1036" alt="Screen Shot 2022-03-01 at 9 49 55 pm" src="https://user-images.githubusercontent.com/23260676/156182761-13aa7e2b-4173-42d5-bd88-ff9b6af238f6.png">
<img width="1036" alt="Screen Shot 2022-03-01 at 9 47 57 pm" src="https://user-images.githubusercontent.com/23260676/156182769-875b1602-1f08-4a19-858e-149ca2f1240e.png">

**Comment by mvulcano-ptc** [comment]
Interesting. So the script is failing when trying to obtain the default database thing from Base Default Manager Configuration. Can you go to PTC.Base.Manager, and take a screen shot of the DefaultGlobalManagerConfiguration, and attach it? I am looking for the record for PTC.DBConnection.Manager. 

This value should get populated automatically when the DBConnection building block is deployed. I am curious if there is an issue here.

It should look like this: 

![image](https://user-images.githubusercontent.com/90467480/156184730-dde93c53-1195-46f7-88f5-aa918ae747a2.png)

**Comment by mpalladi** [comment]
That plus a few others seem to be missing. Possibly a problem when DPM is not installed ?
<img width="1036" alt="Screen Shot 2022-03-01 at 10 15 35 pm" src="https://user-images.githubusercontent.com/23260676/156185643-b2eb6f34-f958-423f-b404-a56c35cb9be0.png">

**Comment by mvulcano-ptc** [comment]
Yeah thats interesting. It looks like this is a bug with the MFGCommon install and not Solution Framework. You will need to create a tech support ticket with PTC Tech Support to figure out what is going on, as they own the DPM and MFGCommon Installation.

Once they can get you through the MFG Common installation, and it is configured properly, then the Solution Framework should work properly. Unfortunately it is dependent on a successful configuration.

If you wanted to go about it yourself, you could try to set each building block's EntryPoint's deploymentState property to 'Not Configured', and attempt to run the InitializeSolution service again. That should trigger the configs to happen. However, it might put things in a bad state if the solution is half-deployed. For example, if the database is already populated. 

- Navigate to Composer -> Things
- Filter on *.EntryPoint
- For each EntryPoint thing
- Open to the Entry Point Properties page
- Set the componentDeploymentState property to 'Not Configured'
- Repeat for each Entry Point thing
- Re-run the PTC.Base.Manager Initialize Solution service.

I would ensure that you have a means to re-create your environment before you attempt to correct it yourself.

Sorry I can't help more, as this doesn't seem to be an issue with the Solution Framework directly.

**Comment by mpalladi** [comment]
That technique did not work for me, as you expected. I had to manually uninstall the BB extension packages in specific order for dependencies, and re deploy.

One thing I noted - it's not possible to uninstall the solution framework extension, at least it leaves behind PTCDTS.Base which can't seem to be removed easily - at least I could not and had no more time to delve into the logs to find the cause.

But in any case, you provided enough information for me to persist and finally get it working , thanks !
